Dataset:
    name: 'Dataset'
    dir: '/teamspace/studios/this_studio/dataset/unlabeled'
    phase: 'deploy'
    dev_set_size: null
    batch_size: 1
    num_workers: 8
    num_channels: 3
    image_size: 64
    num_observed_frames: 11
    num_predict_frames: 11
    test_num_observed_frames: 11
    test_num_predict_frames: 11
    rand_Tp: null
    rand_predict: False
    half_fps: False

STDiff:
    Diffusion:
        unet_config:
            sample_size: 64
    DiffNet:
        MotionEncoder:
            image_size: 64

TestCfg:
    ckpt_path: '/teamspace/studios/this_studio/out/STDiff_ckpts/'
    test_results_path: '/teamspace/studios/this_studio/out/STDiff_ckpts/test'
    scheduler: 
        sample_steps: 100

    metrics: ['PSNR', 'SSIM', 'LPIPS', 'InterLPIPS']
        
