Dataset:
    name: 'Object-Data'
    dir: '/teamspace/studios/this_studio/dataset/unlabeled'
    train: False
    batch_size: 2
    num_workers: 8
    num_channels: 3
    image_size: 64
    num_observed_frames: 11
    num_predict_frames: 11
    test_num_observed_frames: 11
    test_num_predict_frames: 11
    rand_Tp: null
    rand_predict: False

STDiff:
    Diffusion:
        unet_config:
            sample_size: 64
    DiffNet:
        MotionEncoder:
            image_size: 64

TestCfg:
    ckpt_path: '/teamspace/studios/this_studio/stdiff_80_epochs/'
    test_results_path: '/teamspace/studios/this_studio/out/test'
    scheduler: 
        sample_steps: 100

        
